7.6.3 = https://github.com/Bearsampp/module-powershell/releases/download/2026.6.25/bearsampp-powershell-7.6.3-2026.6.25.7z
7.6.2 = https://github.com/Bearsampp/module-powershell/releases/download/2026.6.25/bearsampp-powershell-7.6.2-2026.6.25.7z
7.6.1 = https://github.com/Bearsampp/module-powershell/releases/download/2026.6.25/bearsampp-powershell-7.6.1-2026.6.25.7z
7.6.0 = https://github.com/Bearsampp/module-powershell/releases/download/2026.6.25/bearsampp-powershell-7.6.0-2026.6.25.7z
7.5.4 = https://github.com/Bearsampp/module-powershell/releases/download/2026.6.25/bearsampp-powershell-7.5.4-2026.6.25.7z
