7.6.2 = https://github.com/Bearsampp/module-powershell/releases/download/2026.5.31/bearsampp-powershell-7.6.2-2026.5.31.7z
7.6.1 = https://github.com/Bearsampp/module-powershell/releases/download/2026.4.24/bearsampp-powershell-7.6.1-2026.4.24.7z
7.6.0 = https://github.com/Bearsampp/module-powershell/releases/download/2026.424/bearsampp-powershell-7.6.0-2026.4.24.7z
7.5.4 = https://github.com/Bearsampp/module-powershell/releases/download/2026.424/bearsampp-powershell-7.5.4-2026.4.24.7z
