powershellVersion = "7.6.1"
powershellExe = "pwsh.exe"
powershellLaunchExe = "powershell.bat"
powershellConf = "config\Microsoft.PowerShell_profile.ps1"
powershellFont = "CaskaydiaMono NF"
powershellRows = "33"
powershellCols = "110"

bundleRelease = "@RELEASE_VERSION@"
